all: Main.java Owner.java Pet.java Tiger.java Eagle.java Attribute.java Serialization.java
    javac Main.java Owner.java Pet.java Tiger.java Eagle.java Attribute.java Serialization.java

run: all
    java Main

clean:
    rm*class